// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixMembershipTypes2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixMembershipTypes2));
        
        string IMigrationMetadata.Id
        {
            get { return "202304281648398_FixMembershipTypes2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
